name: Issue & PR Labeler

on:
  issues:
    types: [ opened ]
  pull_request:
    types: [ opened ]

permissions:
  contents: read
  issues: write
  checks: write
  pull-requests: write

jobs:
  label-tag:
    runs-on: ubuntu-latest
    steps:
      - name: add label 2zerozu
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.actor, '2zerozu') }}
        with:
          labels: 영주

      - name: add label jinsu
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.actor, 'jinsu4755') }}
        with:
          labels: 진수

      - name: add label Bug
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, 'Bug:') }}
        with:
          labels: bug

      - name: add label Chore
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, 'Chore:') }}
        with:
          labels: chore

      - name: add label Document
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, 'Docs:') }}
        with:
          labels: documentation

      - name: add label Feature
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, 'Feat:') }}
        with:
          labels: enhancement

      - name: add label Hotfix
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.pull_request.title, 'Hotfix:') }}
        with:
          labels: Hotfix